databases:
  - name: David_post_db
    plan: free
    databaseName: david_post_db  # Corrected: Use only the database name here
    user: david_post_db_user    # Corrected: Ensure the username is a valid SQL identifier

services:
  - type: web
    plan: free
    name: mysite
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn core.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: David_post_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
