databases:
  - name: David_post_db
    plan: free
    databaseName: postgresql://david_post_db_user:B69Scr5t7Spmv0jAmSF3qCq2qBNT5KP8@dpg-ctvqu70gph6c73cf0hv0-a.oregon-postgres.render.com/david_post_db
    user: David_post_db

services:
  - type: web
    plan: free
    name: mysite
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn core.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: David_post_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4