# Generated by Django 5.1.3 on 2025-01-10 20:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('photo', models.ImageField(upload_to='')),
                ('address', models.CharField(max_length=50, unique=True)),
                ('verification_status', models.CharField(choices=[('passport', 'Passport'), ('national_id', 'National ID'), ('driver_license', 'Driver License')], max_length=40)),
                ('id_number', models.CharField(max_length=50, unique=True)),
                ('document', models.FileField(upload_to='kyc_documents/')),
                ('verified', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
