# Generated by Django 5.1.3 on 2025-01-10 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='verification_status',
            field=models.CharField(choices=[('national_id', 'National ID'), ('driver_license', 'Driver License'), ('passport', 'Passport')], max_length=40),
        ),
    ]
